### ISSUE TITLE
主动接口文档？

### ISSUE THREAD

**Issue by ryuujo1573** [jerrita/saaya#1]
Hi, 我非常喜欢这样简洁易懂的设计美学，我希望之后可以用Saaya代替我手写mirai-api-http，期待更多的demo-based文档

**Comment by jerrita** [comment]
感谢对 Saaya 的支持。你可以使用 PyCharm 进行开发，一般可使用 event.bot 获取 bot 实例，接下来便可直接通过 代码内文档 得到所有主动接口说明以及参数列表。

此外，由于 Saaya 用户量不高，故接口多为常用，未全部实现。若有需求，可以提 Issue，或者参考代码风格，更改 session.py 与 protocol.py 后提交 pr 参与贡献。

**Comment by tommyme** [comment]
怎么有人这么懒
